#!/usr/bin/env python

import sys
import os
import unittest

sys.path.append(os.path.join(os.path.dirname( __file__ ), '..'))

from artifuse import ArtiFusion

class TestArtiFusion(unittest.TestCase):
    def setUp(self):
        input_table = "test_input_table.csv"
        working_dir = "test"
        reference_genome = "Homo_sapiens.GRCh38.dna.primary_assembly.fa" # too large to commit (can be downloaded from http://ftp.ensembl.org/pub/release-97/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz)
        bed_file = "test.bed"
        gene_symbols_file = "test_gene_symbols.tsv"

        self.af = ArtiFusion(input_table, working_dir, reference_genome, bed_file, gene_symbols_file)


    def test_get_longest_transcript(self):
        self.assertEqual(self.af.get_longest_transcript("MTIF3"), "ENST00000381116")
        self.assertEqual(self.af.get_longest_transcript("BRCA1"), "ENST00000471181")
        self.assertEqual(self.af.get_longest_transcript("BRAF"), "ENST00000496384")
        self.assertEqual(self.af.get_longest_transcript("PLEKHN1"), "ENST00000379409")
        self.assertEqual(self.af.get_longest_transcript("ATAD3B"), "ENST00000472194")

    def test_rev_comp(self):
        self.assertEqual(self.af.rev_comp("ACGT"), "ACGT")
        self.assertEqual(self.af.rev_comp("ATTG"), "CAAT")

    def test_determine_bp_1(self):
        # ENST00000379487
        self.assertEqual(
            self.af.determine_bp_1(
                [41061508, 41062643, 41065015, 41065163, 41068560, 41071526, 41072781, 41076043, 41080645, 41082703],
                [167, 73, 63, 124, 177, 47, 76, 194, 164, 1303],
                "13",
                0.5,
                2388,
                "+"
            ),
            ('TGAGGAGGTAGATTTGGAACTTCCAAGCACTGAAAATGAGTATGTATCAACTTCAGAAGCTGATGGTGGCGGAGAACCCAAAGTGGTATTTAAAGAAAAAACAGTCACTTCTCTTGGAGTTATGGCAGATGGAGTGGCCCCAGTCTTCAAAAAGAGAAGAACTGAAAATGGAAAATCTAGAAATTTAAGGCAACGAGGTGATGATCAATAGTTGCAGGAGAGCTTTTTGTACATGCTTTTAGGACAGAATGGAGACTTATACACCCAAAGTTTATCTGTGTTTGTTTGTAAGTATTATGATGCTAAAAATTTAGATTTATTCTAAATGTATTTGATGTGAATTAAAATAAATATTTTTTCATGTGAAATTTATTTTGGTTCCTAAAATGGAAGCCTACCACATTGCATTGTAATACAGTGTATTATGTTCAGTGTCTAAAAACTGCTAATTAAGTCATAATTTAAGATGCTATGTATCTGTTATTTAAAACATGGAGAAACAGGGCCTTTATTCCATTCATATTCATAAGAGCATATTTATCCTGCATTGAAAATGCATTACTTTTGCACATTGATATTAACTGTTGTCCAACAAATAAGTATCGGAGTACGTGAGAATATTCCCAGCCCAGTGATGATTTGGTTCTGAGGCTGATGTGAGAAAGCTGATGTAAAAAATGTATGCATATTGGCTTACCTTACTCAATTTAAAGTCAAAAGCCAACAGCCAGGAGCAGCTCAGGTACTTCAGATGTGCTTAATATGGAGTGAAAACTGGACCAGAGGTGGAAAGATGTATTTGCCCCAGTTCACTTCAAAGCAGCAAACGTTGTTTAAGCATTTTAGTTTGAACCAGGCATTGTGTTAGGAATCCAGGGATAAAGATGAATGAAATGTATTTCTGTTCTTCAGGAGTTCACATTCTAGCATATGCCTTTTTTCCCCCAGTCATGCACTCTTTTTAGCAGTCTTATATGTACTAGAAAAGATTTTTTAAAGTTTATTTAAAGCTGTGTAGATGAAGGCTTGATCTAAAATAGTATAAGGTCTCCAGCTTCAGTAAAAGTTTTTAGTGTTTACTTAAATTAGTAATTTCTCACTTTCTGTCTGGTTAAAATGTCTTAAAAAGTAGAATTTTCTTCTTTAATCCGTTTAGTAGTTACCTCCCTTTTACTTTTCAAATTCACAAAATTACATTTCTCATAAATTGTATAGTATTTAACTTATAATAGTTAATATTTGTCTTTTTAAGATGACTGTACATGTAAGAAAAAAGCTTATTAAAAACTTGATCAAAGAATAA', 1303, '13:41080809:+', [('13', 41082703, 41084006)])
        )
        self.assertEqual(
            self.af.determine_bp_1(
                [27435642, 27437115, 27439988, 27441016, 27445087, 27449851, 27450508],
                [251, 158, 461, 61, 50, 67, 56], 
                "13", 
                0.5, 
                1104, 
                "-"
            ), 
            ('GATGGCTGCTCTTTTTCTAAAGAGGTTAACACTACAAACTGTAAAGTCTGAAAATAGTTGCATTAGATGTTTTGGTAAACACATCCTGCAAAAGACAGCACCAGCACAGTTGTCCCCTATTGCTTCTGCCCCAAGACTCTCCTTCCTAATTCATGCAAAAGCCTTTAGTACCGCTGAAGACACCCAGAATGAAGGAAAAAAGACAAAAAAGAATAAAACAGCTTTTAGTAACGTTGGAAGAAAAATTAGTCAGCGAGTTATTCACTTATTTGATGAGAAGGGCAATGATTTGGGAAACATGCACCGAGCAAATGTGATTAGACTTATGGATGAGCGAGACCTGCGACTGGTTCAAAGGAACACCAGCACAGAACCTGCAGAGTATCAGCTCATGACAGGATTGCAGATCCTCCAGGAGCGGCAGAGGCTGAGGGAGATGGAGAAGGCGAACCCCAAAACTGGACCAACCCTGAGAAAGGAACTGATTTTGTCTTCAAATATTGGACAACATGATTTGGACACAAAGACTAAACAGATTCAGCAGTGGATTAAGAAAAAACACCTAGTCCAGATTACCATAAAGAAAGGAAAAAATGTAGACGTGTCAGAAAATGAAATGGAGGAGATATTTCATCAAATACTCCAGACTATGCCTGGAATAGCTACATTCTCATCTAGGCCACAAGCTGTTCAAGGAGGAAAAGCTTTAATGTGTGTTCTTCGTGCTTTCAGCAAAAATGAGGAGAAGGCATATAAAGAAACTCAAGAGACCCAGGAAAGAGACACTTTGAACAAAGACCATGGAAATGATAAGGAATCAAATGTTCTGCATCAGTAATTTTAATAAAGAAAAGCATGCTCTGAGAGAAA', 870, '13:27441016:-', [('13', 27435642, 27435893), ('13', 27437115, 27437273), ('13', 27439988, 27440449)])
        )
        self.assertEqual(
            self.af.determine_bp_1(
                [27435642, 27437115, 27439988, 27441016, 27445087, 27449851, 27450508],
                [251, 158, 461, 61, 50, 67, 56], 
                "13", 
                0.8, 
                1104, 
                "-"
            ), 
            ('CCTACTTGATGTGAAGACAATGAGGATGAAGACCTTTATGGTGATCCACTTCCACTTAATAGATGGCTGCTCTTTTTCTAAAGAGGTTAACACTACAAACTGTAAAGTCTGAAAATAGTTGCATTAGATGTTTTGGTAAACACATCCTGCAAAAGACAGCACCAGCACAGTTGTCCCCTATTGCTTCTGCCCCAAGACTCTCCTTCCTAATTCATGCAAAAGCCTTTAGTACCGCTGAAGACACCCAGAATGAAGGAAAAAAGACAAAAAAGAATAAAACAGCTTTTAGTAACGTTGGAAGAAAAATTAGTCAGCGAGTTATTCACTTATTTGATGAGAAGGGCAATGATTTGGGAAACATGCACCGAGCAAATGTGATTAGACTTATGGATGAGCGAGACCTGCGACTGGTTCAAAGGAACACCAGCACAGAACCTGCAGAGTATCAGCTCATGACAGGATTGCAGATCCTCCAGGAGCGGCAGAGGCTGAGGGAGATGGAGAAGGCGAACCCCAAAACTGGACCAACCCTGAGAAAGGAACTGATTTTGTCTTCAAATATTGGACAACATGATTTGGACACAAAGACTAAACAGATTCAGCAGTGGATTAAGAAAAAACACCTAGTCCAGATTACCATAAAGAAAGGAAAAAATGTAGACGTGTCAGAAAATGAAATGGAGGAGATATTTCATCAAATACTCCAGACTATGCCTGGAATAGCTACATTCTCATCTAGGCCACAAGCTGTTCAAGGAGGAAAAGCTTTAATGTGTGTTCTTCGTGCTTTCAGCAAAAATGAGGAGAAGGCATATAAAGAAACTCAAGAGACCCAGGAAAGAGACACTTTGAACAAAGACCATGGAAATGATAAGGAATCAAATGTTCTGCATCAGTAATTTTAATAAAGAAAAGCATGCTCTGAGAGAAA', 931, '13:27445087:-', [('13', 27435642, 27435893), ('13', 27437115, 27437273), ('13', 27439988, 27440449), ('13', 27441016, 27441077)])
        )

    def test_determine_bp_2(self):
        self.assertEqual(
            self.af.determine_bp_2(
                [27435642, 27437115, 27439988, 27441016, 27445087, 27449851, 27450508], 
                [251, 158, 461, 61, 50, 67, 56], 
                "13", 
                870, 
                "-"
            ), 
            (3, '13:27441078:-')
        )


#    def test_swap(self):
#        self.assertEqual(self.af.swap([100, 200, 300], [10, 20, 30], "2", "-", 2, "ACGT", 4), "TATCGACGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGGCGCTAGCTACATACGACGATCGATCGATCGATCGATGCGCGATCGATCGATNNNNNNNNNNATCGATCGATCTAGCTAGCGACTAGCGACTGACTGATCGATCGGCGCTACGATCGATCGATCGATCTATCGACTAGCTGACTGATCGACGNNNNNNNNNNNNNNNNNNNNCTAGCTAGCTAGCTAGTTGCGACTAGCATGCTAGCATGCTACTAGCTACGATGCATCTATCTGACGATTACTGACATCGANNNNNNNNNNNNNNNNNNNNNNNNNNACGTCGTAGCTAGCTAGCTAGCTAGCTA")
#        self.assertEqual(self.af.swap([100, 200, 300], [10, 20, 30], "2", "+", 2, "ACGT", 4), "TATCGACGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGGCGCTAGCTACATACGACGATCGATCGATCGATCGATGCGCGATCGATCGATCGATCGATCGATCGATCGATCTAGCTAGCGACTAGCGACTGACTGATCGATCGGCGCTACGATCGATCGATCGATCTATCGACTAGCTGACTGATCGACGGCATCGATCGGATCAGCTAGCTAGCTAGCTAGCTAGTTGCGACTAGCATGCTAGCATGCTACTAGCTACGATGCATCTATCTGACGATTACTGACATCGAACGTNNNNNNNNNNNNNNNNNNNNNNNNNNCGTAGCTAGCTAGCTAGCTAGCTA")

if __name__ == '__main__':
    unittest.main()
